### ISSUE TITLE
摄影师的联系方式

### ISSUE THREAD

**Issue by iyaozhen** [iyaozhen/biyezhao#1]
这里的意思是摄影师的联系方式还包括微信号？

![qq 20150331135540](https://cloud.githubusercontent.com/assets/4395553/6913119/1815d2c0-d7ae-11e4-8aff-ab1e41855c09.png)

**Comment by polandeme** [comment]
1. 微信号加上感觉挺好的(非必须)  
2. 评论其他用户加入的必要性不是太大吧。  
:innocent:

**Comment by iyaozhen** [comment]
评论其他用户这个是畅言插件自带的功能。

**Comment by polandeme** [comment]
@iyaozhen  嗯，这样就简单多啦。:smile:
